### ISSUE TITLE
"Report a bug" link/button

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#106]
- [x] add a link to this issue tracker
- [x] add a "Report a bug" part to [README.md](https://github.com/ufal/perl-pmltq-web/blob/master/README.md), where both the issue tracker and an e-mail address are mentioned

**Comment by matyaskopp** [comment]
report bug button: fa1725b6a275cfd74613b8048c4718a3c30b8429

**Comment by matyaskopp** [comment]
readme: 69d2e2b104ac21a2d49d87a1c570d1c4b24f3e89

**Comment by matyaskopp** [comment]
contact: a89d0b0ed47d5b95a3406d222cb7dbefe0e153cd
