### ISSUE TITLE
A tiny bug in "Suggest"

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#112]
Run [this query](http://hdl.handle.net/11346/PMLTQ-A4WP), go to second tree, select nodes `$a` and `$b` and run "Sugget".  It should not be possible to untick the line with `];` above the empty line - it gets unticked automatically together with the first line `t-node $a := [`.

I think it may be due to a regexp that does not expect the semicolon separating two separate subqueries.

**Comment by matyaskopp** [comment]
fixed with 0ea969e4ab494091e004408ccb783162ca7414df
(not deployed yet)
