### ISSUE TITLE
corpus list, missing tag: parallel

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#114]
Add a "parallel" tag for parallel corpora (= corpora with more than one language).

**Comment by Ansa211** [comment]
missing tags:
- [ ] *parallel*: Prague Czech-English Dependency Treebank (both 2.0 and 3.0)
- [ ] *PDT*: Prague Czech-English Dependency Treebank (2.0, 3.0, Czech Part only)
- [ ] Hyderabad Treebank - Bangla Train Set: *Bangla*
- [ ] Merlin Train Data: *Czech*, *learner*
- [ ] Penn Discourse Treebank 2.0: *English*, *Penn Treebank*

dále navrhuju upravit "Featured treebanks":
- [ ] nahradit pdt 2.5 -> pdit 2.0 (Prague Discourse Treebank: je to nejnovější verze pdt dat, kterou máme)
- [ ] dát tam PCEDT 3.0 (nejnovější paralelní korpus, který máme)
- [ ] přidat Penn CU Chinese Treebank (je to jeden z mála frázových korpusů, které máme, navíc to je v exotických písmenkách) nebo jiný korpus ze skupiny Penn Treebank (aby bylo vidět, že umíme i frázové treebanky)

**Comment by matyaskopp** [comment]
Featured treebanks related issue: https://github.com/ufal/perl-pmltq-web/issues/61
