### ISSUE TITLE
zamrzající mouseover

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#117]
![zamrzly_potvory](https://user-images.githubusercontent.com/1833866/30920617-ba73643c-a3a4-11e7-8ca0-4ae4f0977dab.png)

výpis z konzole:

![chyby_tam_jsou](https://user-images.githubusercontent.com/1833866/30920622-bdd77456-a3a4-11e7-8448-7e38459b7cc4.png)

Matyáš wins: 
![image_480](https://user-images.githubusercontent.com/1833866/30920625-c1c72c32-a3a4-11e7-8b1b-139ffd3136dd.png)

je to nejspíš když kliknu na tlačítko a rychle uhnu na jiné
a pak nejspíš zpět

**Comment by matyaskopp** [comment]
a6aadcd68aa93ceb0407f89fe94be3ba20f6f767
