### ISSUE TITLE
Do not select a query when switching between query lists

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#120]
current situation:

I open a query list, select a query and decide to edit it a little bit and save it to a different list; so I switch to that different list, edit the query and click "Save" - and this overwrites one of the queries that were already present in that list, because on opening a list, the system thinks that I am editing one of that list's queries, even though it does NOT change the content of the editing window

in Czech:
V tom momentu, kdy přepnu mezi seznamy, tak pml-tq mi ponechá stejný dotaz v editovacím okně, ale myslí si, že otevřelo query z toho nového seznamu.
A to mě mate, protože dál edituju v okně, dám "save", a ejhle, přepíše se mi query, kterou jsem ani neviděla otevřenou.

ideal solution: on switching to a new query list, do not open any query of that list (or automatically open a "new" query, which is what happens in tred) so that there is no danger of automatically overwriting anything already present

**Comment by matyaskopp** [comment]
![image](https://user-images.githubusercontent.com/5867995/31165010-9fedeb9c-a8e9-11e7-8ccf-6370f6e056ec.png)

fixed with 0725ad77187e05a648fc6bd9ef2dc385c8aa0ff5
