### ISSUE TITLE
Update HamleDT in PML-TQ

### ISSUE THREAD

**Issue by dan-zeman** [ufal/perl-pmltq-web#13]
HamleDT 2.0 is the current version that should be accessible via PML-TQ. 14 treebanks should be available for everyone (Bulgarian + those listed as "Free" at http://ufal.mff.cuni.cz/hamledt/obtaining-hamledt), the rest only for signed-in users. The Russian treebank only for people from ÚFAL (or, if we cannot determine who is from ÚFAL, it could be available for people from the Charles University).

Every sentence in HamleDT 2.0 has three trees side-by-side: the original tree, Prague-style tree and Stanford-style tree.

**Comment by dan-zeman** [comment]
Update: The current goal is to have a subset of HamleDT 3.0 in PML-TQ (only those treebanks that are not part of Universal Dependencies 1.1), and Universal Dependencies 1.1 (all treebanks, under this name, not as HamleDT).

We are almost there, but the list of treebanks presented to the user is outdated. Under HamleDT it lists the languages that were in HamleDT 2.0. If they do not fulfill the above condition (i.e. if they are part of UD 1.1), the link is simply wrong (for example, selecting HamleDT Basque will give you Arabic data). Under Universal Dependencies it lists only those languages that were already in UD 1.0 (even if the data are actually from 1.1). The new languages are not accessible.

**Comment by m1ch4ls** [comment]
@dan-zeman Is it ok? Can I close the issue?

**Comment by dan-zeman** [comment]
It looks OK now. I have not checked the (un)availability of the HamleDT Russian treebank though (I cannot pretend I am a user from outside the Charles University, who should not get access).

**Comment by dan-zeman** [comment]
We are going to need to update the data again. HamleDT 3.0 was released last week and the data are not identical to those that are currently in PML-TQ.

**Comment by dan-zeman** [comment]
It would be very useful if every a-node in HamleDT had the attribute zone, which would be the language code and selector, as displayed at the root. We often want to limit the query to one of the three trees that appear in each bundle.

**Comment by dan-zeman** [comment]
Closing this issue. It has not been solved completely but it is now somewhat obsolete (as is HamleDT 3.0); the focus should go to Universal Dependencies 2.0.
