### ISSUE TITLE
PDiT2.0: how to access m-layer attributes - suggested query leads to empty output,

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#130]
According to the `Node Types` menu, the corpus should contain nodes of type m-node.
However, the query [`m-node []`](http://hdl.handle.net/11346/PMLTQ-P4KJ) has an empty output.

Another way how to access the information from the m-layer in PDT-corpora is usually as an `m/something` attribute on the a-layer. However, although the menu `Attributes > of a-node` contains the value `m/form`, the query [`a-node [m/form ~ '.*']`](http://hdl.handle.net/11346/PMLTQ-WM1U) has an empty output. (The same query works in [PDT 3.0](http://hdl.handle.net/11346/PMLTQ-ZMQD)!)

The `Suggest` function does not help either: 
Go to [PDiT 2.0](http://lindat.mff.cuni.cz/services/pmltq/#!/treebank/pdit20/query/) and enter a simple query for an a-node [`a-node []`](http://hdl.handle.net/11346/PMLTQ-KTTZ).
Select the first node and use the Suggest function to create the following queries; both queries lead to empty output od PDiT2.0 but have some output on PDT 3.0:
[`a-node $a :=  [
  member m [
    form = 'unie',
  ],
]`](http://hdl.handle.net/11346/PMLTQ-0MMO)  vs.  the same in [PDT 3.0](http://hdl.handle.net/11346/PMLTQ-RWYT)
[`a-node $a :=  [
  member m [
    member w/[1] [
      token = 'unie',
    ],
  ],
]`](http://hdl.handle.net/11346/PMLTQ-CPH7)   vs.  the same in [PDT 3.0](http://hdl.handle.net/11346/PMLTQ-GNDA)

**Comment by matyaskopp** [comment]
suggest is based on files in pml format but the query is evaluated on database. 
`m-node` table in postgres database is empty thus query result is empty too.

file `/net/work/projects/pmltq/data/pdit20/sql_dump/adata__type_m-node.dump` is not empty so I guess that it was incorrectly imported to database.

**Comment by matyaskopp** [comment]
Fixed treebanks: **pdit20**, **pdit20_full**

Treebanks were converted with wrong mdata_30_schema.xml schema.
