### ISSUE TITLE
Jumping to a different result does not work

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#131]
This is about the editable number field in ![editable_number_field](https://user-images.githubusercontent.com/1833866/34412263-74ec027c-ebdc-11e7-9b04-9ebc5a79c4eb.png)

**What does NOT work:**   change the number -> *press enter* -> the displayed sentence changes
**What works:**        change the number to 1 less or 1 more than the number of the sentence I want to jump to -> *press the corresponding arrow* -> the displayed sentence changes

**Comment by matyaskopp** [comment]
How it works? change number and leave the focus of field.
@Ansa211 : You want to make it works after pressing enter?

If you are on 1st sentence, than change it to 2 and then press "Following sentence..", than it jumps to minimum of 3 and number of sentences. (you leave the focus and then press next)

**Comment by Ansa211** [comment]
Yes, my intuitive expectation was that I have to press enter (or there could be a "Go" button or something like that).

Leaving focus is an unintuitive concept for me. Even after your explanation, I find it strange that nothing happens when I change the number in the field, but the sentence is redrawn when I click somewhere else.

**Comment by matyaskopp** [comment]
a7b304ab00e5a186cebf0374634e23e12b4b4553
