### ISSUE TITLE
PDiT 2.0: trees with no annotation

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#133]
[PDiT2.0, search for any a-node](http://hdl.handle.net/11346/PMLTQ-STKJ)

When I click the "following context" arrow, I get the following view:

![following_context](https://user-images.githubusercontent.com/1833866/34647591-39dc421c-f386-11e7-91fe-faa94bc10574.png)

I thought this is somehow related to the fact that I used the "following context" button, but I am getting the same empty tree after clicking five times "next result" (even after clearing the cache).

**Comment by matyaskopp** [comment]
I have cleared server cache. It seems that it works.
