### ISSUE TITLE
Add Slovenian treebank 

### ISSUE THREAD

**Issue by stranak** [ufal/perl-pmltq-web#25]
http://hdl.handle.net/11858/00-097C-0000-0022-F59C-8 At least it seems to be a treebank :confused: 

> "each sentence with it syntactic dependency relations"

**Comment by dan-zeman** [comment]
I am not sure whether this is the latest version. I have been in touch with Kaja Dobrovoljc and Tomaž Erjavec recently about this. They have a 500Kwords treebank which might be a newer version of this and they are very interested in seeing it in PML-TQ.

I asked @m1ch4ls to add it together with HamleDT and UD but I think there was an issue with space on euler. (I have written a Treex reader for the TEI-XML format they use, so the data is available in the treex format.)

**Comment by stranak** [comment]
> Recently I was in touch with Kaja Dobrovoljc and Tomaž Erjavec about this. They have a 500Kwords treebank which might be a newer version of this and they are very interested in seeing it in PML-TQ.

OK, thanks, @dan-zeman I found the newer treebank: http://hdl.handle.net/11356/1029 So I updated our record for jos100 (above) as "replaced by" this new, so now it tells you clearly there is a new version and you should probably get that. (The first time we did this between two repositories)

This ssj500k 1.3 looks like it has 235864 tokens of Slovenian (taken from the CoNLL version). There seems to be also English in TEI, but I have no idea, whether it is parallel. If so, it would be very nice. If not, it might still be quite interesting.

**Comment by dan-zeman** [comment]
Thanks to @m1ch4ls it is already there (https://lindat.mff.cuni.cz/services/pmltq/ssj/) but it has to be updated so that values of the `deprel` attribute are visible in the tree (instead of the two red exclamation marks).

**Comment by dan-zeman** [comment]
The treebank is now part of UD so I am closing this issue.
