### ISSUE TITLE
Fix query history

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq-web#3]
TODO list for history:

- [ ] Global history doesn't show treebank name and doesn't allow to run/edit query
- [ ] Name your queries
- [ ] Categories for history
- [ ] Deleting queries

**Comment by stranak** [comment]
More TODOs:

- [ ] Add queries made remotly from Tred to the history

**Comment by m1ch4ls** [comment]
I am closing this and moving everything to #9
