### ISSUE TITLE
Suggest does not work

### ISSUE THREAD

**Issue by dan-zeman** [ufal/perl-pmltq-web#39]
When I click on a node and then on "Suggest", I see attributes from the next node in the sentence. (I do not need to suggest a query, I just want to see the attributes of the node :-))

**Comment by dan-zeman** [comment]
It is not always the next node. Now I got a node that does not even appear in this sentence.

**Comment by dan-zeman** [comment]
And sometimes it just works OK...
Strange.

**Comment by matyaskopp** [comment]
works for me

3666670329ebbc40087f4031f5b0006e010b3307 and https://github.com/ufal/pmltq-print-server/issues/1
