### ISSUE TITLE
Fix generated help

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq-web#43]
The most basic example is missing.

![image](https://cloud.githubusercontent.com/assets/1168605/9712779/5bac0a14-554d-11e5-9ffb-44100d2c276e.png)

**Comment by dan-zeman** [comment]
BTW I am usually starting with `a-node []`, but recently I found out that `a-root []` may be more useful—because pressing the "next result" button shows the next tree, it does not just highlight the next node in the current tree.
