### ISSUE TITLE
Too large RegExp in WebKit

### ISSUE THREAD

**Issue by m1ch4ls** [ufal/perl-pmltq-web#51]
```
Error: Invalid regular expression: regular expression too large
RegExp@[native code]
```

**Comment by matyaskopp** [comment]
Error appears only when option LINDAT=true is set while building.

**Comment by stranak** [comment]
In Safari on macOS 10.12.3 I now see the queries fine for some treebanks (e.g. CoNLL Chinese, Sinica, Chinese Treebank) and still empty for some other (UD ZH (Chinese)).

**Comment by stranak** [comment]
As I wrote in #66, I propose to disregard possible problems in other WebKit browsers (usually quite old and virtually unused) and concentrate on testing only Safari (from WebKit browsers).

**Comment by matyaskopp** [comment]
quick fix: ignore ace highlighter in help and public queries list

**Comment by matyaskopp** [comment]
this fix works for pdt like schemas: a2da7f2e1d577b514fee49064b7399262644de93

**Comment by matyaskopp** [comment]
TODO: fix treex schema

**Comment by matyaskopp** [comment]
fixing treex schema 79fc0fbcc6c6b0e305ea2ee1581ecbab29bcb162

this is probably the last fix because I have removed higher part of unicode table from regex.
