### ISSUE TITLE
editing a query list keeps reloading a previously saved version

### ISSUE THREAD

**Issue by Ansa211** [ufal/perl-pmltq-web#98]
I tried to create, edit and annotate a query list, and although I occasionally see a message saying "List has been saved", when I try to annotate a query (the , the whole "My queries" page reloads and I see the list with no of the changes present...

steps to reproduce:
- go to My queries -> select a previously saved query list
- click on "Editor" next to "Description:", edit the entry field, click on "Preview" (I see "List has been saved")
- click on a down arrow on the left side of one of the queries in the list -> Editor -> edit the entry field -> click on "Preview"...
.... at this point, I lose my edits :-(

I am using 
Chromium Version 60.0.3112.113 (Developer Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit)

**Comment by matyaskopp** [comment]
fixed with 11a3a3c98ac7c12646a4d1c5910b87bcbe46d194
