### ISSUE TITLE
query list is not sorted

### ISSUE THREAD

**Issue by jonathanverner** [ufal/perl-pmltq-web#99]
When using a saved query list, the order of the queries in the drop-down menu does not reflect the order one has created using "My queries". And it is not alphabetical either, so starting the names of the queries with numbers does not help much.

You can test this with my public list:
https://lindat.mff.cuni.cz/services/pmltq/#!/treebank/pdt30/queryfile/34?userID=223

**Comment by matyaskopp** [comment]
0cfc4275470369b2c0af02637be4b8394ed03b3c
